Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\core\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\core\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /admin HTTP/1.1" 301 0
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4185
"GET /static/admin/css/base.css HTTP/1.1" 200 21310
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2694
"GET /static/admin/css/responsive.css HTTP/1.1" 200 18559
"GET /static/admin/css/login.css HTTP/1.1" 200 958
"GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2929
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
"GET /static/admin/js/theme.js HTTP/1.1" 200 1943
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2324
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 5846
"GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\shamba\admin.py changed, reloading.
C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\shamba\admin.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\shamba\admin.py changed, reloading.
C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\shamba\admin.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\shamba\admin.py changed, reloading.
C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\shamba\admin.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\shamba\admin.py changed, reloading.
C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\shamba\admin.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /admin/ HTTP/1.1" 200 7314
"GET /admin/shamba/user/ HTTP/1.1" 200 9426
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /static/admin/css/changelists.css HTTP/1.1" 200 6566
"GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
"GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
"GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 8943
"GET /static/admin/js/core.js HTTP/1.1" 200 5682
"GET /static/admin/js/actions.js HTTP/1.1" 200 7872
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 292458
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381
"GET /static/admin/js/filters.js HTTP/1.1" 200 978
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
"GET /admin/shamba/user/1/change/ HTTP/1.1" 200 23477
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /static/admin/css/forms.css HTTP/1.1" 200 9090
"GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
"GET /static/admin/js/calendar.js HTTP/1.1" 200 8466
"GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19319
"GET /static/admin/css/widgets.css HTTP/1.1" 200 11921
"GET /static/admin/js/change_form.js HTTP/1.1" 200 606
"GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
"GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
Internal Server Error: /admin/shamba/user/1/change/
Traceback (most recent call last):
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\db\backends\base\base.py", line 312, in _commit
    return self.connection.commit()
           ^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.ForeignKeyViolation: insert or update on table "django_admin_log" violates foreign key constraint "django_admin_log_user_id_c564eba6_fk_auth_user_id"
DETAIL:  Key (user_id)=(1) is not present in table "auth_user".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\contrib\admin\options.py", line 1889, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\contrib\admin\options.py", line 1746, in changeform_view
    with transaction.atomic(using=router.db_for_write(self.model)):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\db\transaction.py", line 263, in __exit__
    connection.commit()
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\db\backends\base\base.py", line 336, in commit
    self._commit()
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\db\backends\base\base.py", line 311, in _commit
    with debug_transaction(self, "COMMIT"), self.wrap_database_errors:
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\db\backends\base\base.py", line 312, in _commit
    return self.connection.commit()
           ^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: insert or update on table "django_admin_log" violates foreign key constraint "django_admin_log_user_id_c564eba6_fk_auth_user_id"
DETAIL:  Key (user_id)=(1) is not present in table "auth_user".

"POST /admin/shamba/user/1/change/ HTTP/1.1" 500 147266
"GET /admin/shamba/user/1/change/ HTTP/1.1" 200 23684
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
"GET /admin/shamba/user/add/ HTTP/1.1" 200 23038
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /admin/shamba/user/add/ HTTP/1.1" 200 23038
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /admin/shamba/user/ HTTP/1.1" 200 9426
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /admin/shamba/user/1/change/ HTTP/1.1" 200 23477
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
Internal Server Error: /admin/shamba/user/1/change/
Traceback (most recent call last):
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\db\backends\base\base.py", line 312, in _commit
    return self.connection.commit()
           ^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.ForeignKeyViolation: insert or update on table "django_admin_log" violates foreign key constraint "django_admin_log_user_id_c564eba6_fk_auth_user_id"
DETAIL:  Key (user_id)=(1) is not present in table "auth_user".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\contrib\admin\options.py", line 1889, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\contrib\admin\options.py", line 1746, in changeform_view
    with transaction.atomic(using=router.db_for_write(self.model)):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\db\transaction.py", line 263, in __exit__
    connection.commit()
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\db\backends\base\base.py", line 336, in commit
    self._commit()
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\db\backends\base\base.py", line 311, in _commit
    with debug_transaction(self, "COMMIT"), self.wrap_database_errors:
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\db\backends\base\base.py", line 312, in _commit
    return self.connection.commit()
           ^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: insert or update on table "django_admin_log" violates foreign key constraint "django_admin_log_user_id_c564eba6_fk_auth_user_id"
DETAIL:  Key (user_id)=(1) is not present in table "auth_user".

"POST /admin/shamba/user/1/change/ HTTP/1.1" 500 147266
"GET /admin/shamba/user/1/change/ HTTP/1.1" 200 23684
"GET /admin/shamba/user/1/change/ HTTP/1.1" 200 23477
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
Internal Server Error: /admin/shamba/user/1/change/
Traceback (most recent call last):
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\db\backends\base\base.py", line 312, in _commit
    return self.connection.commit()
           ^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.ForeignKeyViolation: insert or update on table "django_admin_log" violates foreign key constraint "django_admin_log_user_id_c564eba6_fk_auth_user_id"
DETAIL:  Key (user_id)=(1) is not present in table "auth_user".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\contrib\admin\options.py", line 1889, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\contrib\admin\options.py", line 1746, in changeform_view
    with transaction.atomic(using=router.db_for_write(self.model)):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\db\transaction.py", line 263, in __exit__
    connection.commit()
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\db\backends\base\base.py", line 336, in commit
    self._commit()
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\db\backends\base\base.py", line 311, in _commit
    with debug_transaction(self, "COMMIT"), self.wrap_database_errors:
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\PC\Desktop\shambarecords\shambarecordsbackend\venv\Lib\site-packages\django\db\backends\base\base.py", line 312, in _commit
    return self.connection.commit()
           ^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: insert or update on table "django_admin_log" violates foreign key constraint "django_admin_log_user_id_c564eba6_fk_auth_user_id"
DETAIL:  Key (user_id)=(1) is not present in table "auth_user".

"POST /admin/shamba/user/1/change/ HTTP/1.1" 500 147266
"GET /admin/shamba/user/1/change/ HTTP/1.1" 200 23684
"GET /admin/shamba/user/1/change/ HTTP/1.1" 200 23474
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /admin/shamba/user/1/change/ HTTP/1.1" 200 23474
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /admin/shamba/user/ HTTP/1.1" 200 9425
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /admin/shamba/user/1/change/ HTTP/1.1" 200 23474
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
Method Not Allowed: /api/v1/auth/register/
"GET /api/v1/auth/register/ HTTP/1.1" 405 40
Bad Request: /api/v1/auth/register/
"POST /api/v1/auth/register/ HTTP/1.1" 400 87
Bad Request: /api/v1/auth/register/
"POST /api/v1/auth/register/ HTTP/1.1" 400 45
Bad Request: /api/v1/auth/register/
"POST /api/v1/auth/register/ HTTP/1.1" 400 151
Bad Request: /api/v1/auth/register/
"POST /api/v1/auth/register/ HTTP/1.1" 400 45
Bad Request: /api/v1/auth/register/
"POST /api/v1/auth/register/ HTTP/1.1" 400 45
Bad Request: /api/v1/auth/register/
"POST /api/v1/auth/register/ HTTP/1.1" 400 45
"POST /api/v1/auth/register/ HTTP/1.1" 201 268
Bad Request: /api/v1/auth/login/
"POST /api/v1/auth/login/ HTTP/1.1" 400 108
"POST /api/v1/auth/login/ HTTP/1.1" 200 640
Forbidden: /api/v1/auth/logout/
"POST /api/v1/auth/logout/ HTTP/1.1" 403 45
Forbidden: /api/v1/auth/logout/
"POST /api/v1/auth/logout/ HTTP/1.1" 403 45
Forbidden: /api/v1/auth/logout/
"POST /api/v1/auth/logout/ HTTP/1.1" 403 45
Forbidden: /api/v1/auth/logout/
"POST /api/v1/auth/logout/ HTTP/1.1" 403 45
Forbidden: /api/v1/dashboard/admin/
"GET //api/v1/dashboard/admin/ HTTP/1.1" 403 63
Forbidden: /api/v1/auth/login/
"POST /api/v1/auth/login/ HTTP/1.1" 403 45
Forbidden: /api/v1/auth/login/
"POST /api/v1/auth/login/ HTTP/1.1" 403 45
"GET //api/v1/dashboard/farmer/ HTTP/1.1" 200 75
Not Found: /api/v1/profile/ 
"GET /api/v1/profile/%20 HTTP/1.1" 404 4507
"GET /api/v1/profile/ HTTP/1.1" 200 170
